# Generated by Django 5.0.2 on 2024-03-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tegs_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tegs',
            new_name='NewTegs',
        ),
        migrations.RemoveField(
            model_name='post',
            name='link',
        ),
    ]
