# Generated by Django 5.0.2 on 2024-03-11 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_tegs_newtegs_remove_post_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newtegs',
            old_name='name_teg',
            new_name='nameTeg',
        ),
    ]
