# Generated by Django 5.0.2 on 2024-03-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(default='http://placehold.it/900x300', verbose_name='Картинка'),
        ),
    ]
