# Generated by Django 5.0.2 on 2024-03-13 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_tegs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tegs',
            name='links',
        ),
    ]
