# Generated by Django 5.0.2 on 2024-03-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_tegs_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='tegs',
            name='links',
            field=models.ManyToManyField(to='blog.post'),
        ),
    ]
