# Generated by Django 5.0.2 on 2024-03-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_tegs_links'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewTegs',
        ),
        migrations.RemoveField(
            model_name='tegs',
            name='links',
        ),
        migrations.AddField(
            model_name='post',
            name='links',
            field=models.ManyToManyField(to='blog.tegs'),
        ),
    ]
