# Generated by Django 5.0.2 on 2024-03-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_delete_newtegs_remove_tegs_links_post_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tegs',
            name='name_tags',
            field=models.CharField(max_length=32, verbose_name='Name tegs'),
        ),
    ]
