# Generated by Django 5.0.2 on 2024-03-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_tegs_name_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailName', models.TextField(verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Почта',
                'verbose_name_plural': 'Почты',
            },
        ),
    ]
